# Application
ios_app_id                                : 1459042137
ios_app_country                           : us
appstore_link                             : https://apps.apple.com/app/raivo-otp/id1459042137?platform=iphone
presskit_download_link                    : https://github.com/raivo-otp/ios-application/tree/master/Assets
app_icon                                  : assets/app-icon.png
app_name                                  : Raivo OTP
app_name_short                            : Raivo
app_subtitle                              : Simply the best authenticator
app_description                           : A native, lightweight, non-commercial and secure multi-factor authenticator that synchronises your one-time passwords across all of your Apple devices.
twitter_username                          : RaivoOTP
github_username                           : raivo
github_community                          : https://github.com/raivo-otp/ios-application/graphs/contributors

jekyll_get_json:
  - data: changelog
    json: 'https://api.github.com/repos/raivo-otp/ios-application/releases'

# Features
features                                  :
  - title                                 : Synchronisation
    description                           : Sync your one-time passwords to iCloud and never lose access to them again.
    fontawesome_icon_name                 : magic
  - title                                 : Local backup
    description                           : Stay in control. Export your one-time passwords to encrypted ZIP archives.
    fontawesome_icon_name                 : star
  - title                                 : Customisation
    description                           : Add (custom) icons to your one-time passwords and apply effects to them.
    fontawesome_icon_name                 : mobile
  - title                                 : Raivo for MacOS
    description                           : Use the MacOS companion app to send your one-time passwords to your Mac.
    fontawesome_icon_name                 : adjust
  - title                                 : Powerfull search
    description                           : Search through all of your one-time passwords with one tap under your thumb.
    fontawesome_icon_name                 : sync
  - title                                 : Native & open source
    description                           : Experience the fast native app built in Swift 5. And it's open source too!
    fontawesome_icon_name                 : arrow-alt-circle-down

# Theme
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"
cover_image                               : assets/headerimage.jpeg
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8
body_background_color                     : "#ffffff"
link_color                                : "#ec1438"
app_title_color                           : "#ffffff"
app_subtitle_color                        : "#ffffff"
app_description_color                     : "#ffffff"
feature_title_color                       : "#000000"
feature_text_color                        : "#666666"
feature_icons_foreground_color            : "#ec1438"
feature_icons_background_color            : "#e6e6e6"
social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"
footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - CNAME
  - CONTRIBUTING.md
  - LICENSE.md
  - PRIVACY.md
  - README.md
  - SECURITY.md

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-get-json
 # - jekyll-github-metadata

# Markdown rendering
markdown: kramdown
